[package]
name = "sqlshim"
version = "0.1.0"
edition = "2024"

[lib]
crate-type = ["cdylib"]

[dependencies]
libc = "0.2"
regex = "1"
sqlparser = "0.60"

[features]
default = ["sqlsec", "sqlaudit"]
sqlsec = []
sqlaudit = []
