on: [push, pull_request]

name: Continuous integration

jobs:
  cargo:
    name: Cargo
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          # - stable
          - beta
          # - nightly
    steps:
      - run: wget https://sqlite.org/2026/sqlite-tools-linux-x64-3510200.zip && unzip sqlite-tools-linux-x64-3510200.zip -d sqlite-tools
      - run: echo "$(pwd)/sqlite-tools" >> $GITHUB_PATH
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy, rust-src
      - uses: Swatinem/rust-cache@v2
      - name: check
        run: cargo check
      - name: format check
        run: cargo fmt --all -- --check
      - name: clippy
        run: cargo clippy -- -D warnings
      - name: build
        run: cargo build
      - name: tests
        run: cargo test --features ci

  markdown:
    name: Markdown lint
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actionshub/markdownlint@v3.1.4

  mdbook:
    name: MdBook
    runs-on: ubuntu-latest
    strategy:
      matrix:
        toolchain:
          # - stable
          - beta
          # - nightly
    steps:
      - uses: actions/checkout@v4
      - uses: actions-rust-lang/setup-rust-toolchain@v1
        with:
          toolchain: ${{ matrix.toolchain }}
          components: rustfmt, clippy
      - run: |
          tag=$(curl 'https://api.github.com/repos/rust-lang/mdbook/releases/latest' | jq -r '.tag_name')
          url="https://github.com/rust-lang/mdbook/releases/download/${tag}/mdbook-${tag}-x86_64-unknown-linux-gnu.tar.gz"
          mkdir bin
          curl -sSL $url | tar -xz --directory=bin
          echo "$(pwd)/bin" >> $GITHUB_PATH
      - run: |
          cd docs
          mdbook build
